namespace Certification70_483._02_CreateAndUseTypes._05_FindExecuteCreateTypesAtRunTimeUsingReflection
{
    /// <summary>
    /// The automatically generated source file
    /// </summary>
    public static class Example76
    {
        public static void Start()
        {
            /*
            //------------------------------------------------------------------------------
                // <auto-generated>
                // This code was generated by a tool.
                // Runtime Version:4.0.30319.18010
                //
                // Changes to this file may cause incorrect behavior and will be lost if
                // the code is regenerated.
                // </auto-generated>
                //------------------------------------------------------------------------------
                namespace MyNamespace {
                 using System;
                 public class MyClass {
                 public static void Main() {
                 Console.WriteLine(“Hello World!”);
                 }
                 }
             */
        }
    }
}
